"""Initial schema: app + audit schemas, base tables, overlap constraint, append-only audit.

Hand-written rather than autogenerated because the two things that make this
schema correct (the exclusion constraint and the append-only audit guarantees)
are invisible to Alembic's autogenerate.

Revision ID: 0001
Revises:
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ACTIVE = "('hold','scheduled','confirmed','checked_in')"
DOC_TYPES = "('CC','TI','CE','PA','RC','PE','PPT','MS','AS','CN')"


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS app")
    op.execute("CREATE SCHEMA IF NOT EXISTS audit")
    # Required for the exclusion constraint: lets GiST index the scalar doctor_id
    # alongside the range column.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    op.create_table(
        "clinics",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("timezone", sa.String(64), nullable=False, server_default="America/Bogota"),
        sa.Column("locale", sa.String(16), nullable=False, server_default="es-CO"),
        sa.Column(
            "settings", postgresql.JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        schema="app",
    )

    op.create_table(
        "patients",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "clinic_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.clinics.id"),
            nullable=False,
        ),
        sa.Column("document_type", sa.String(4), nullable=False),
        sa.Column("document_number", sa.LargeBinary, nullable=False),
        sa.Column("document_number_bidx", sa.LargeBinary, nullable=False),
        sa.Column("given_names", sa.LargeBinary, nullable=False),
        sa.Column("family_names", sa.LargeBinary, nullable=False),
        sa.Column("birth_date", sa.Date, nullable=True),
        sa.Column("phone_e164", sa.LargeBinary, nullable=True),
        sa.Column("phone_e164_bidx", sa.LargeBinary, nullable=True),
        sa.Column("email", sa.LargeBinary, nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.CheckConstraint(f"document_type IN {DOC_TYPES}", name="ck_patients_document_type_valid"),
        schema="app",
    )
    op.create_index(
        "ix_patients_clinic_phone_bidx",
        "patients",
        ["clinic_id", "phone_e164_bidx"],
        schema="app",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_patients_clinic_document",
        "patients",
        ["clinic_id", "document_type", "document_number_bidx"],
        unique=True,
        schema="app",
    )

    op.create_table(
        "phone_bindings",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "clinic_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.clinics.id"),
            nullable=False,
        ),
        sa.Column("phone_e164_bidx", sa.LargeBinary, nullable=False),
        sa.Column(
            "patient_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.patients.id"),
            nullable=False,
        ),
        sa.Column("relationship_kind", sa.String(20), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        schema="app",
    )
    op.create_index(
        "uq_phone_bindings_clinic_phone_patient",
        "phone_bindings",
        ["clinic_id", "phone_e164_bidx", "patient_id"],
        unique=True,
        schema="app",
    )

    op.create_table(
        "consents",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "clinic_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.clinics.id"),
            nullable=False,
        ),
        sa.Column(
            "patient_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.patients.id"),
            nullable=False,
        ),
        sa.Column("purpose", sa.String(40), nullable=False),
        sa.Column("channel", sa.String(20), nullable=True),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evidence_kind", sa.String(40), nullable=False),
        sa.Column("evidence_ref", sa.String(500), nullable=True),
        sa.Column("policy_version", sa.String(40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        schema="app",
    )
    op.create_index(
        "ix_consents_lookup",
        "consents",
        ["clinic_id", "patient_id", "purpose"],
        schema="app",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )

    op.create_table(
        "doctors",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "clinic_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.clinics.id"),
            nullable=False,
        ),
        sa.Column("full_name", sa.String(200), nullable=False),
        sa.Column("specialty", sa.String(100), nullable=False),
        sa.Column("active", sa.Boolean, nullable=False, server_default=sa.text("true")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        schema="app",
    )

    op.create_table(
        "locations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "clinic_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.clinics.id"),
            nullable=False,
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("address", sa.String(300), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        schema="app",
    )

    op.create_table(
        "availability_rules",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "clinic_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.clinics.id"),
            nullable=False,
        ),
        sa.Column(
            "doctor_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.doctors.id"),
            nullable=False,
        ),
        sa.Column(
            "location_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.locations.id"),
            nullable=False,
        ),
        sa.Column("weekday", sa.SmallInteger, nullable=False),
        sa.Column("start_time", sa.Time, nullable=False),
        sa.Column("end_time", sa.Time, nullable=False),
        sa.Column("valid_from", sa.Date, nullable=False),
        sa.Column("valid_until", sa.Date, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.CheckConstraint("end_time > start_time", name="ck_availability_rules_time_window_ordered"),
        sa.CheckConstraint("weekday BETWEEN 0 AND 6", name="ck_availability_rules_weekday_range"),
        schema="app",
    )

    op.create_table(
        "availability_exceptions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "clinic_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.clinics.id"),
            nullable=False,
        ),
        sa.Column(
            "doctor_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.doctors.id"),
            nullable=False,
        ),
        sa.Column("on_date", sa.Date, nullable=False),
        sa.Column("kind", sa.String(20), nullable=False),
        sa.Column("start_time", sa.Time, nullable=True),
        sa.Column("end_time", sa.Time, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        schema="app",
    )

    op.create_table(
        "appointment_types",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "clinic_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.clinics.id"),
            nullable=False,
        ),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("duration_minutes", sa.Integer, nullable=False),
        sa.Column("buffer_minutes", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column("sensitivity", sa.String(10), nullable=False, server_default="normal"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        schema="app",
    )

    op.create_table(
        "appointments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "clinic_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.clinics.id"),
            nullable=False,
        ),
        sa.Column(
            "patient_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.patients.id"),
            nullable=False,
        ),
        sa.Column(
            "doctor_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.doctors.id"),
            nullable=False,
        ),
        sa.Column(
            "location_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.locations.id"),
            nullable=False,
        ),
        sa.Column(
            "appointment_type_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("app.appointment_types.id"),
            nullable=False,
        ),
        sa.Column("during", postgresql.TSTZRANGE, nullable=False),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(120), nullable=True, unique=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.CheckConstraint(
            "(status <> 'hold') OR (expires_at IS NOT NULL)",
            name="ck_appointments_hold_requires_expiry",
        ),
        schema="app",
    )

    # ADR-16 / ADR-17. This is the single most important line in the schema:
    # the database refuses an overlapping booking or hold for the same doctor,
    # regardless of what the application does.
    op.execute(
        f"""
        ALTER TABLE app.appointments
        ADD CONSTRAINT no_overlapping_active_appointments
        EXCLUDE USING gist (doctor_id WITH =, during WITH &&)
        WHERE (status IN {ACTIVE})
        """
    )

    # ---------------- audit schema ----------------
    op.create_table(
        "access_log",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column(
            "occurred_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("clinic_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("actor_kind", sa.String(20), nullable=False),
        sa.Column("actor_id", sa.String(120), nullable=True),
        sa.Column("patient_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("action", sa.String(20), nullable=False),
        sa.Column("resource", sa.String(60), nullable=False),
        sa.Column("resource_id", sa.String(120), nullable=True),
        sa.Column("purpose", sa.String(60), nullable=False),
        sa.Column("channel", sa.String(20), nullable=True),
        sa.Column("request_id", sa.String(64), nullable=True),
        sa.Column("ip", postgresql.INET, nullable=True),
        sa.Column("processor", sa.String(60), nullable=True),
        sa.Column("processor_model", sa.String(80), nullable=True),
        sa.Column("fields_disclosed", postgresql.ARRAY(sa.String), nullable=True),
        sa.Column("zero_retention", sa.Boolean, nullable=True),
        sa.Column("prev_hash", sa.LargeBinary, nullable=True),
        sa.Column("row_hash", sa.LargeBinary, nullable=True),
        schema="audit",
    )
    op.create_index(
        "ix_access_log_patient_time", "access_log", ["patient_id", "occurred_at"], schema="audit"
    )

    # Append-only, mechanism 1: a trigger that refuses mutation outright.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit.reject_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit.access_log is append-only (attempted %)', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER access_log_append_only
        BEFORE UPDATE OR DELETE ON audit.access_log
        FOR EACH ROW EXECUTE FUNCTION audit.reject_mutation();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS access_log_append_only ON audit.access_log")
    op.execute("DROP FUNCTION IF EXISTS audit.reject_mutation()")
    op.drop_table("access_log", schema="audit")
    op.execute("ALTER TABLE app.appointments DROP CONSTRAINT IF EXISTS no_overlapping_active_appointments")
    for table in (
        "appointments",
        "appointment_types",
        "availability_exceptions",
        "availability_rules",
        "locations",
        "doctors",
        "consents",
        "phone_bindings",
        "patients",
        "clinics",
    ):
        op.drop_table(table, schema="app")
    op.execute("DROP SCHEMA IF EXISTS audit CASCADE")
    op.execute("DROP SCHEMA IF EXISTS app CASCADE")
